merge
This is a combination of 4 commits.

merge

merge conflicts fix

Terribly stupid git merge markers made it in.

add forgotten FORMAT ~b, ~o

remerge

Sanity check compilation strings.

When  hacking on  the compiler,  particularly the  reader/code generator
bits, I've  made some  mistakes that could  create invalid  streams with
things like Null or  Page chars that will not work  with either Node nor
Firefox (at least).

This prevents emitting invalid strings, at least.

Also, fix buffer creation to avoid NULL bytes when prelude.js is Unicode

Tests for Unicode, numeric radix

Note that these will usually crash the master branch.

Adapt to upstream MAKE-NEW

Mass-reformat

Misc. test improvements

Relax the assertions a bit

just a funny inline indent

flip back reversed CHECK-TYPE args

Functions capture `this' value in the `cl::this' variable

Declare JS variable for the `cl::this` binding

merged ok

Use “var” rather than “let”

Something(?) introduces an error here,
        let trampoline = function(values){
        ^^^
SyntaxError: Unexpected strict mode reserved word

For now, just using “var” works.

Simple FFI unit tests, Part 1.

Report Navigator info as Machine

Implementations ofmachine-type, software-type, et al.

Add Node.js support for machine-type &c

Trivial unit tests for machine info

remove leading space on CPU

ensure no "" strings either

null-if-empty

EMPTYP

parens error after merge

PRINT &OPTIONAL STREAM

Also TERPRI

ignore *.orig

some tests of printing numbers

particularly the “#x-ff” case that I'd done incorrectly.

PRIN1 in tests

also a missing “-” on one test case

PRINT &OPTIONAL STREAM

Also TERPRI

some tests of printing numbers

particularly the “#x-ff” case that I'd done incorrectly.

print sign after sharp radix/*print-radix*

PRINT &OPTIONAL STREAM

Also TERPRI

PRIN1 in tests

also a missing “-” on one test case

warnings and such

DEFPACKAGE :EXPORT handler

define FFI package. Need to merge in from other branch.

Rebase from upstream master

Also, using the SAFE-JS-FUN-NAME in preference to new JSIZE function
since they serve approximately the same purpose, but the SAFE-JS-*
functions are used throughout this branch already.

Tests for Unicode, numeric radix

Note that these will usually crash the master branch.

merge conflicts fix

Terribly stupid git merge markers made it in.

add forgotten FORMAT ~b, ~o

Fix FORMAT padding. Add docstrings.

uncomment now-working test; add a couple easy other tests

mass reformat; missing )

(a couple of close-parens got lost in the merge)

make

merge

misc mop-ups after merge

annotate IN-PACKAGE bug

Verbose compilation output

failures

reformat

still trouble IDing special-forms

blanket Eval-When

symbols EQL not EQ

legacy before packages

package mismatches, ugh

getting into special forms

indent

make recursion guard more effective/annoying

Misc. bootstrap fixups

document

still trouble with macros/special forms

misc hacks to stage 2 bootstrap

fix deps on make test

Force loading SB-CLTL2 — Travis/Debian doesn't

use REQUIRE not LOAD for SB-CLTL2

add page breaks

add page breaks

Package object, not designator

ensure Bordeaux-Threads are loaded

Travis-CI starts with a virgin image with no packages
loaded, but Quicklisp should be available. This will
(hopefully) ensure it loads the Bordeaux-Threads
system through Quicklisp.

remove /DEBUG calls, no longer needed

Break up compiler built-ins into files

PACKAGE object, not package-name

Remove /DEBUG forms (no longer needed)

ignore .ansi-patched

identify funny file

Travis: Use Trusty Tahr

EVAL to get global binding

JSCL/CL package, do not redefine CL

move definition of *BUILTINS*

move back var def, stupid

Travis test

- Adding more numeric functions

reflow

parentheses, not parents

Functions capture `this' value in the `cl::this' variable

MAKE-NEW operator

Working after major simplifications.

Easier than it smelled…

Usage: (jscl::make-new |ClassConstructor| arg₁ arg₂ …)

Support for radix, Unicode

Bundled  set  of changes  to  support  reading  and printing  things  in
arbitrary numeric radix 2-36;

char-name/name-char "U+xxxx" names

PRINC/FORMAT ~A corrections in a few cases

Partial to reasonable support in FORMAT for:

    ~a ~s ~w
    ~d ~x ~NNr
    ~% ~& ~|

Also bundled in are fixes  for SUBSTITUTE[-IF[-NOT]] and EVERY, as these
were dependencies.

Apply more meaningful names to vars in generated Javascript

*read-base* and *print-base* support

PARSE-INTEGER

Correction to Javascript in CHAR-UPCASE in edge cases

Misc fixes discovered during the implementation of the above.

Tests for Unicode, numeric radix

Note that these will usually crash the master branch.

merge conflicts fix

Terribly stupid git merge markers made it in.

remerge

Adapt to upstream MAKE-NEW

Mass-reformat

Misc. test improvements

just a funny inline indent